// CastleService — read/control RPCs served by Castle and consumed by Parapet
// (and any human tooling such as grpcurl).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: overlord/v1/castle.proto

package overlordv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Overseer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "online" | "offline"
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overseer) Reset() {
	*x = Overseer{}
	mi := &file_overlord_v1_castle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overseer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overseer) ProtoMessage() {}

func (x *Overseer) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overseer.ProtoReflect.Descriptor instead.
func (*Overseer) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{0}
}

func (x *Overseer) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

func (x *Overseer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Overseer) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Overseer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Overseer) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Overseer) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type ListOverseersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOverseersRequest) Reset() {
	*x = ListOverseersRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOverseersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOverseersRequest) ProtoMessage() {}

func (x *ListOverseersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOverseersRequest.ProtoReflect.Descriptor instead.
func (*ListOverseersRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{1}
}

func (x *ListOverseersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOverseersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOverseersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overseers     []*Overseer            `protobuf:"bytes,1,rep,name=overseers,proto3" json:"overseers,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOverseersResponse) Reset() {
	*x = ListOverseersResponse{}
	mi := &file_overlord_v1_castle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOverseersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOverseersResponse) ProtoMessage() {}

func (x *ListOverseersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOverseersResponse.ProtoReflect.Descriptor instead.
func (*ListOverseersResponse) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{2}
}

func (x *ListOverseersResponse) GetOverseers() []*Overseer {
	if x != nil {
		return x.Overseers
	}
	return nil
}

func (x *ListOverseersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetOverseerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverseerRequest) Reset() {
	*x = GetOverseerRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverseerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverseerRequest) ProtoMessage() {}

func (x *GetOverseerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverseerRequest.ProtoReflect.Descriptor instead.
func (*GetOverseerRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{3}
}

func (x *GetOverseerRequest) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // optional filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{4}
}

func (x *ListRunsRequest) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

func (x *ListRunsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_overlord_v1_castle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{5}
}

func (x *ListRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{6}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListRunEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"` // exclusive
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunEventsRequest) Reset() {
	*x = ListRunEventsRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunEventsRequest) ProtoMessage() {}

func (x *ListRunEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunEventsRequest.ProtoReflect.Descriptor instead.
func (*ListRunEventsRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{7}
}

func (x *ListRunEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ListRunEventsRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *ListRunEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Envelope            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunEventsResponse) Reset() {
	*x = ListRunEventsResponse{}
	mi := &file_overlord_v1_castle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunEventsResponse) ProtoMessage() {}

func (x *ListRunEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunEventsResponse.ProtoReflect.Descriptor instead.
func (*ListRunEventsResponse) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{8}
}

func (x *ListRunEventsResponse) GetEvents() []*Envelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListRunEventsResponse) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type WatchRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"` // exclusive; 0 streams from the beginning
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRunRequest) Reset() {
	*x = WatchRunRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunRequest) ProtoMessage() {}

func (x *WatchRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunRequest.ProtoReflect.Descriptor instead.
func (*WatchRunRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{9}
}

func (x *WatchRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WatchRunRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

type StopRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{10}
}

func (x *StopRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StopRunRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ServerTime when the cancel was issued; the run may still take time to
	// observe and react to the cancel.
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_overlord_v1_castle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{11}
}

func (x *StopRunResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type SendPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptRequest) Reset() {
	*x = SendPromptRequest{}
	mi := &file_overlord_v1_castle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptRequest) ProtoMessage() {}

func (x *SendPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptRequest.ProtoReflect.Descriptor instead.
func (*SendPromptRequest) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{12}
}

func (x *SendPromptRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SendPromptRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *SendPromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type SendPromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptResponse) Reset() {
	*x = SendPromptResponse{}
	mi := &file_overlord_v1_castle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptResponse) ProtoMessage() {}

func (x *SendPromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_castle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptResponse.ProtoReflect.Descriptor instead.
func (*SendPromptResponse) Descriptor() ([]byte, []int) {
	return file_overlord_v1_castle_proto_rawDescGZIP(), []int{13}
}

func (x *SendPromptResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

var File_overlord_v1_castle_proto protoreflect.FileDescriptor

const file_overlord_v1_castle_proto_rawDesc = "" +
	"\n" +
	"\x18overlord/v1/castle.proto\x12\voverlord.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18overlord/v1/events.proto\x1a\x1aoverlord/v1/overseer.proto\"\xcc\x02\n" +
	"\bOverseer\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\x06labels\x18\x03 \x03(\v2!.overlord.v1.Overseer.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12?\n" +
	"\rregistered_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12<\n" +
	"\flast_seen_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x14ListOverseersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"t\n" +
	"\x15ListOverseersResponse\x123\n" +
	"\toverseers\x18\x01 \x03(\v2\x15.overlord.v1.OverseerR\toverseers\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"5\n" +
	"\x12GetOverseerRequest\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\"\x7f\n" +
	"\x0fListRunsRequest\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"`\n" +
	"\x10ListRunsResponse\x12$\n" +
	"\x04runs\x18\x01 \x03(\v2\x10.overlord.v1.RunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"&\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"`\n" +
	"\x14ListRunEventsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"a\n" +
	"\x15ListRunEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.overlord.v1.EnvelopeR\x06events\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\"E\n" +
	"\x0fWatchRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\"?\n" +
	"\x0eStopRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x0fStopRunResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"V\n" +
	"\x11SendPromptRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"M\n" +
	"\x12SendPromptResponse\x127\n" +
	"\tissued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt2\xdf\x04\n" +
	"\rCastleService\x12V\n" +
	"\rListOverseers\x12!.overlord.v1.ListOverseersRequest\x1a\".overlord.v1.ListOverseersResponse\x12E\n" +
	"\vGetOverseer\x12\x1f.overlord.v1.GetOverseerRequest\x1a\x15.overlord.v1.Overseer\x12G\n" +
	"\bListRuns\x12\x1c.overlord.v1.ListRunsRequest\x1a\x1d.overlord.v1.ListRunsResponse\x126\n" +
	"\x06GetRun\x12\x1a.overlord.v1.GetRunRequest\x1a\x10.overlord.v1.Run\x12V\n" +
	"\rListRunEvents\x12!.overlord.v1.ListRunEventsRequest\x1a\".overlord.v1.ListRunEventsResponse\x12A\n" +
	"\bWatchRun\x12\x1c.overlord.v1.WatchRunRequest\x1a\x15.overlord.v1.Envelope0\x01\x12D\n" +
	"\aStopRun\x12\x1b.overlord.v1.StopRunRequest\x1a\x1c.overlord.v1.StopRunResponse\x12M\n" +
	"\n" +
	"SendPrompt\x12\x1e.overlord.v1.SendPromptRequest\x1a\x1f.overlord.v1.SendPromptResponseB\xac\x01\n" +
	"\x0fcom.overlord.v1B\vCastleProtoP\x01Z?github.com/brokenbots/overlord/shared/pb/overlord/v1;overlordv1\xa2\x02\x03OXX\xaa\x02\vOverlord.V1\xca\x02\vOverlord\\V1\xe2\x02\x17Overlord\\V1\\GPBMetadata\xea\x02\fOverlord::V1b\x06proto3"

var (
	file_overlord_v1_castle_proto_rawDescOnce sync.Once
	file_overlord_v1_castle_proto_rawDescData []byte
)

func file_overlord_v1_castle_proto_rawDescGZIP() []byte {
	file_overlord_v1_castle_proto_rawDescOnce.Do(func() {
		file_overlord_v1_castle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_overlord_v1_castle_proto_rawDesc), len(file_overlord_v1_castle_proto_rawDesc)))
	})
	return file_overlord_v1_castle_proto_rawDescData
}

var file_overlord_v1_castle_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_overlord_v1_castle_proto_goTypes = []any{
	(*Overseer)(nil),              // 0: overlord.v1.Overseer
	(*ListOverseersRequest)(nil),  // 1: overlord.v1.ListOverseersRequest
	(*ListOverseersResponse)(nil), // 2: overlord.v1.ListOverseersResponse
	(*GetOverseerRequest)(nil),    // 3: overlord.v1.GetOverseerRequest
	(*ListRunsRequest)(nil),       // 4: overlord.v1.ListRunsRequest
	(*ListRunsResponse)(nil),      // 5: overlord.v1.ListRunsResponse
	(*GetRunRequest)(nil),         // 6: overlord.v1.GetRunRequest
	(*ListRunEventsRequest)(nil),  // 7: overlord.v1.ListRunEventsRequest
	(*ListRunEventsResponse)(nil), // 8: overlord.v1.ListRunEventsResponse
	(*WatchRunRequest)(nil),       // 9: overlord.v1.WatchRunRequest
	(*StopRunRequest)(nil),        // 10: overlord.v1.StopRunRequest
	(*StopRunResponse)(nil),       // 11: overlord.v1.StopRunResponse
	(*SendPromptRequest)(nil),     // 12: overlord.v1.SendPromptRequest
	(*SendPromptResponse)(nil),    // 13: overlord.v1.SendPromptResponse
	nil,                           // 14: overlord.v1.Overseer.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
	(*Run)(nil),                   // 16: overlord.v1.Run
	(*Envelope)(nil),              // 17: overlord.v1.Envelope
}
var file_overlord_v1_castle_proto_depIdxs = []int32{
	14, // 0: overlord.v1.Overseer.labels:type_name -> overlord.v1.Overseer.LabelsEntry
	15, // 1: overlord.v1.Overseer.registered_at:type_name -> google.protobuf.Timestamp
	15, // 2: overlord.v1.Overseer.last_seen_at:type_name -> google.protobuf.Timestamp
	0,  // 3: overlord.v1.ListOverseersResponse.overseers:type_name -> overlord.v1.Overseer
	16, // 4: overlord.v1.ListRunsResponse.runs:type_name -> overlord.v1.Run
	17, // 5: overlord.v1.ListRunEventsResponse.events:type_name -> overlord.v1.Envelope
	15, // 6: overlord.v1.StopRunResponse.issued_at:type_name -> google.protobuf.Timestamp
	15, // 7: overlord.v1.SendPromptResponse.issued_at:type_name -> google.protobuf.Timestamp
	1,  // 8: overlord.v1.CastleService.ListOverseers:input_type -> overlord.v1.ListOverseersRequest
	3,  // 9: overlord.v1.CastleService.GetOverseer:input_type -> overlord.v1.GetOverseerRequest
	4,  // 10: overlord.v1.CastleService.ListRuns:input_type -> overlord.v1.ListRunsRequest
	6,  // 11: overlord.v1.CastleService.GetRun:input_type -> overlord.v1.GetRunRequest
	7,  // 12: overlord.v1.CastleService.ListRunEvents:input_type -> overlord.v1.ListRunEventsRequest
	9,  // 13: overlord.v1.CastleService.WatchRun:input_type -> overlord.v1.WatchRunRequest
	10, // 14: overlord.v1.CastleService.StopRun:input_type -> overlord.v1.StopRunRequest
	12, // 15: overlord.v1.CastleService.SendPrompt:input_type -> overlord.v1.SendPromptRequest
	2,  // 16: overlord.v1.CastleService.ListOverseers:output_type -> overlord.v1.ListOverseersResponse
	0,  // 17: overlord.v1.CastleService.GetOverseer:output_type -> overlord.v1.Overseer
	5,  // 18: overlord.v1.CastleService.ListRuns:output_type -> overlord.v1.ListRunsResponse
	16, // 19: overlord.v1.CastleService.GetRun:output_type -> overlord.v1.Run
	8,  // 20: overlord.v1.CastleService.ListRunEvents:output_type -> overlord.v1.ListRunEventsResponse
	17, // 21: overlord.v1.CastleService.WatchRun:output_type -> overlord.v1.Envelope
	11, // 22: overlord.v1.CastleService.StopRun:output_type -> overlord.v1.StopRunResponse
	13, // 23: overlord.v1.CastleService.SendPrompt:output_type -> overlord.v1.SendPromptResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_overlord_v1_castle_proto_init() }
func file_overlord_v1_castle_proto_init() {
	if File_overlord_v1_castle_proto != nil {
		return
	}
	file_overlord_v1_events_proto_init()
	file_overlord_v1_overseer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_overlord_v1_castle_proto_rawDesc), len(file_overlord_v1_castle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_overlord_v1_castle_proto_goTypes,
		DependencyIndexes: file_overlord_v1_castle_proto_depIdxs,
		MessageInfos:      file_overlord_v1_castle_proto_msgTypes,
	}.Build()
	File_overlord_v1_castle_proto = out.File
	file_overlord_v1_castle_proto_goTypes = nil
	file_overlord_v1_castle_proto_depIdxs = nil
}
