// Overlord event schema.
//
// The `Envelope` message is the wire format for every event flowing between
// Overseer, Castle, and Parapet. Field numbers in `payload` are **stable** once
// assigned — see WORKSTREAM Phase 1.1 §3.1. A new event type must use the next
// unused field number and never reuse an old one.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: overlord/v1/events.proto

package overlordv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogStream identifies which stream a StepLog chunk came from.
type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
	LogStream_LOG_STREAM_AGENT       LogStream = 3
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
		3: "LOG_STREAM_AGENT",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
		"LOG_STREAM_AGENT":       3,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_overlord_v1_events_proto_enumTypes[0].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_overlord_v1_events_proto_enumTypes[0]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{0}
}

// Envelope is the wire format for every event.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version. Always 1 for this package; bump only with a new
	// `overlord.vN` package.
	SchemaVersion int32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Run the event belongs to.
	RunId string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Castle-assigned monotonic sequence number per run_id. 0 when an Overseer
	// submits; Castle stamps the real value before persistence and fan-out.
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Event timestamp (UTC).
	Ts *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	// Optional correlation id used to match a SubmitEvents envelope with its Ack.
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Typed payload. Field numbers here are permanent.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_RunStarted
	//	*Envelope_RunCompleted
	//	*Envelope_RunFailed
	//	*Envelope_StepEntered
	//	*Envelope_StepOutcome
	//	*Envelope_StepTransition
	//	*Envelope_StepLog
	//	*Envelope_AdapterEvent
	//	*Envelope_OverseerHeartbeat
	//	*Envelope_OverseerDisconnected
	//	*Envelope_WatchReady
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_overlord_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Envelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRunStarted() *RunStarted {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RunStarted); ok {
			return x.RunStarted
		}
	}
	return nil
}

func (x *Envelope) GetRunCompleted() *RunCompleted {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RunCompleted); ok {
			return x.RunCompleted
		}
	}
	return nil
}

func (x *Envelope) GetRunFailed() *RunFailed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RunFailed); ok {
			return x.RunFailed
		}
	}
	return nil
}

func (x *Envelope) GetStepEntered() *StepEntered {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepEntered); ok {
			return x.StepEntered
		}
	}
	return nil
}

func (x *Envelope) GetStepOutcome() *StepOutcome {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepOutcome); ok {
			return x.StepOutcome
		}
	}
	return nil
}

func (x *Envelope) GetStepTransition() *StepTransition {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepTransition); ok {
			return x.StepTransition
		}
	}
	return nil
}

func (x *Envelope) GetStepLog() *StepLog {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StepLog); ok {
			return x.StepLog
		}
	}
	return nil
}

func (x *Envelope) GetAdapterEvent() *AdapterEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AdapterEvent); ok {
			return x.AdapterEvent
		}
	}
	return nil
}

func (x *Envelope) GetOverseerHeartbeat() *OverseerHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OverseerHeartbeat); ok {
			return x.OverseerHeartbeat
		}
	}
	return nil
}

func (x *Envelope) GetOverseerDisconnected() *OverseerDisconnected {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OverseerDisconnected); ok {
			return x.OverseerDisconnected
		}
	}
	return nil
}

func (x *Envelope) GetWatchReady() *WatchReady {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_WatchReady); ok {
			return x.WatchReady
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_RunStarted struct {
	RunStarted *RunStarted `protobuf:"bytes,10,opt,name=run_started,json=runStarted,proto3,oneof"`
}

type Envelope_RunCompleted struct {
	RunCompleted *RunCompleted `protobuf:"bytes,11,opt,name=run_completed,json=runCompleted,proto3,oneof"`
}

type Envelope_RunFailed struct {
	RunFailed *RunFailed `protobuf:"bytes,12,opt,name=run_failed,json=runFailed,proto3,oneof"`
}

type Envelope_StepEntered struct {
	StepEntered *StepEntered `protobuf:"bytes,13,opt,name=step_entered,json=stepEntered,proto3,oneof"`
}

type Envelope_StepOutcome struct {
	StepOutcome *StepOutcome `protobuf:"bytes,14,opt,name=step_outcome,json=stepOutcome,proto3,oneof"`
}

type Envelope_StepTransition struct {
	StepTransition *StepTransition `protobuf:"bytes,15,opt,name=step_transition,json=stepTransition,proto3,oneof"`
}

type Envelope_StepLog struct {
	StepLog *StepLog `protobuf:"bytes,16,opt,name=step_log,json=stepLog,proto3,oneof"`
}

type Envelope_AdapterEvent struct {
	AdapterEvent *AdapterEvent `protobuf:"bytes,17,opt,name=adapter_event,json=adapterEvent,proto3,oneof"`
}

type Envelope_OverseerHeartbeat struct {
	OverseerHeartbeat *OverseerHeartbeat `protobuf:"bytes,18,opt,name=overseer_heartbeat,json=overseerHeartbeat,proto3,oneof"`
}

type Envelope_OverseerDisconnected struct {
	OverseerDisconnected *OverseerDisconnected `protobuf:"bytes,19,opt,name=overseer_disconnected,json=overseerDisconnected,proto3,oneof"`
}

type Envelope_WatchReady struct {
	// WatchReady is a protocol-level sentinel sent once at the start of a
	// WatchRun server-stream, after any persisted-event replay, to flush
	// response headers so the client's WatchRun call can return. It has no
	// associated run state; clients MUST ignore it.
	WatchReady *WatchReady `protobuf:"bytes,99,opt,name=watch_ready,json=watchReady,proto3,oneof"`
}

func (*Envelope_RunStarted) isEnvelope_Payload() {}

func (*Envelope_RunCompleted) isEnvelope_Payload() {}

func (*Envelope_RunFailed) isEnvelope_Payload() {}

func (*Envelope_StepEntered) isEnvelope_Payload() {}

func (*Envelope_StepOutcome) isEnvelope_Payload() {}

func (*Envelope_StepTransition) isEnvelope_Payload() {}

func (*Envelope_StepLog) isEnvelope_Payload() {}

func (*Envelope_AdapterEvent) isEnvelope_Payload() {}

func (*Envelope_OverseerHeartbeat) isEnvelope_Payload() {}

func (*Envelope_OverseerDisconnected) isEnvelope_Payload() {}

func (*Envelope_WatchReady) isEnvelope_Payload() {}

// RunStarted — a run has begun executing.
type RunStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowName  string                 `protobuf:"bytes,1,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	InitialStep   string                 `protobuf:"bytes,2,opt,name=initial_step,json=initialStep,proto3" json:"initial_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStarted) Reset() {
	*x = RunStarted{}
	mi := &file_overlord_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStarted) ProtoMessage() {}

func (x *RunStarted) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStarted.ProtoReflect.Descriptor instead.
func (*RunStarted) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *RunStarted) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunStarted) GetInitialStep() string {
	if x != nil {
		return x.InitialStep
	}
	return ""
}

// RunCompleted — a run reached a terminal state successfully.
type RunCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalState    string                 `protobuf:"bytes,1,opt,name=final_state,json=finalState,proto3" json:"final_state,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCompleted) Reset() {
	*x = RunCompleted{}
	mi := &file_overlord_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompleted) ProtoMessage() {}

func (x *RunCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCompleted.ProtoReflect.Descriptor instead.
func (*RunCompleted) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *RunCompleted) GetFinalState() string {
	if x != nil {
		return x.FinalState
	}
	return ""
}

func (x *RunCompleted) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RunFailed — a run ended in a terminal failure.
type RunFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFailed) Reset() {
	*x = RunFailed{}
	mi := &file_overlord_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFailed) ProtoMessage() {}

func (x *RunFailed) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFailed.ProtoReflect.Descriptor instead.
func (*RunFailed) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *RunFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RunFailed) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

// StepEntered — the engine began executing a step.
type StepEntered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Adapter       string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEntered) Reset() {
	*x = StepEntered{}
	mi := &file_overlord_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEntered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEntered) ProtoMessage() {}

func (x *StepEntered) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEntered.ProtoReflect.Descriptor instead.
func (*StepEntered) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *StepEntered) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepEntered) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *StepEntered) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// StepOutcome — a step finished with a named outcome (or error).
type StepOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepOutcome) Reset() {
	*x = StepOutcome{}
	mi := &file_overlord_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepOutcome) ProtoMessage() {}

func (x *StepOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepOutcome.ProtoReflect.Descriptor instead.
func (*StepOutcome) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *StepOutcome) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepOutcome) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *StepOutcome) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepOutcome) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StepTransition — the FSM moved from one node to another via an outcome.
type StepTransition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	ViaOutcome    string                 `protobuf:"bytes,3,opt,name=via_outcome,json=viaOutcome,proto3" json:"via_outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepTransition) Reset() {
	*x = StepTransition{}
	mi := &file_overlord_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepTransition) ProtoMessage() {}

func (x *StepTransition) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepTransition.ProtoReflect.Descriptor instead.
func (*StepTransition) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *StepTransition) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *StepTransition) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *StepTransition) GetViaOutcome() string {
	if x != nil {
		return x.ViaOutcome
	}
	return ""
}

// StepLog — a chunk of log output from a running step.
type StepLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Stream        LogStream              `protobuf:"varint,2,opt,name=stream,proto3,enum=overlord.v1.LogStream" json:"stream,omitempty"`
	Chunk         string                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepLog) Reset() {
	*x = StepLog{}
	mi := &file_overlord_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepLog) ProtoMessage() {}

func (x *StepLog) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepLog.ProtoReflect.Descriptor instead.
func (*StepLog) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *StepLog) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *StepLog) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *StepLog) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

// AdapterEvent — adapter-specific structured event.
//
// On-wire contract for `data`: adapter sinks SHOULD emit JSON objects
// (top-level `{}`). For backward compatibility with Phase 0 adapters that
// emitted scalars or arrays, the Overseer transport wraps non-object
// payloads under a `value` key before conversion to Struct (e.g. the
// wire payload for the array `[1,2,3]` becomes `{"value": [1,2,3]}`).
// Subscribers MUST tolerate the wrapped shape. New adapters SHOULD
// produce object payloads and avoid relying on the wrapping.
type AdapterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	Adapter       string                 `protobuf:"bytes,2,opt,name=adapter,proto3" json:"adapter,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterEvent) Reset() {
	*x = AdapterEvent{}
	mi := &file_overlord_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterEvent) ProtoMessage() {}

func (x *AdapterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterEvent.ProtoReflect.Descriptor instead.
func (*AdapterEvent) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *AdapterEvent) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *AdapterEvent) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

func (x *AdapterEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// OverseerHeartbeat — periodic liveness signal from an Overseer.
type OverseerHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverseerHeartbeat) Reset() {
	*x = OverseerHeartbeat{}
	mi := &file_overlord_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverseerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerHeartbeat) ProtoMessage() {}

func (x *OverseerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerHeartbeat.ProtoReflect.Descriptor instead.
func (*OverseerHeartbeat) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *OverseerHeartbeat) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

// OverseerDisconnected — Castle observed the Overseer going away.
type OverseerDisconnected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverseerId    string                 `protobuf:"bytes,1,opt,name=overseer_id,json=overseerId,proto3" json:"overseer_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverseerDisconnected) Reset() {
	*x = OverseerDisconnected{}
	mi := &file_overlord_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverseerDisconnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverseerDisconnected) ProtoMessage() {}

func (x *OverseerDisconnected) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverseerDisconnected.ProtoReflect.Descriptor instead.
func (*OverseerDisconnected) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *OverseerDisconnected) GetOverseerId() string {
	if x != nil {
		return x.OverseerId
	}
	return ""
}

func (x *OverseerDisconnected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// WatchReady is a protocol-level sentinel payload sent by WatchRun once at
// stream start. It has no fields and no run-semantic meaning; it exists
// solely to flush Connect server-stream response headers so the client's
// WatchRun call can return before any real event is published.
type WatchReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchReady) Reset() {
	*x = WatchReady{}
	mi := &file_overlord_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchReady) ProtoMessage() {}

func (x *WatchReady) ProtoReflect() protoreflect.Message {
	mi := &file_overlord_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchReady.ProtoReflect.Descriptor instead.
func (*WatchReady) Descriptor() ([]byte, []int) {
	return file_overlord_v1_events_proto_rawDescGZIP(), []int{11}
}

var File_overlord_v1_events_proto protoreflect.FileDescriptor

const file_overlord_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x18overlord/v1/events.proto\x12\voverlord.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\a\n" +
	"\bEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12:\n" +
	"\vrun_started\x18\n" +
	" \x01(\v2\x17.overlord.v1.RunStartedH\x00R\n" +
	"runStarted\x12@\n" +
	"\rrun_completed\x18\v \x01(\v2\x19.overlord.v1.RunCompletedH\x00R\frunCompleted\x127\n" +
	"\n" +
	"run_failed\x18\f \x01(\v2\x16.overlord.v1.RunFailedH\x00R\trunFailed\x12=\n" +
	"\fstep_entered\x18\r \x01(\v2\x18.overlord.v1.StepEnteredH\x00R\vstepEntered\x12=\n" +
	"\fstep_outcome\x18\x0e \x01(\v2\x18.overlord.v1.StepOutcomeH\x00R\vstepOutcome\x12F\n" +
	"\x0fstep_transition\x18\x0f \x01(\v2\x1b.overlord.v1.StepTransitionH\x00R\x0estepTransition\x121\n" +
	"\bstep_log\x18\x10 \x01(\v2\x14.overlord.v1.StepLogH\x00R\astepLog\x12@\n" +
	"\radapter_event\x18\x11 \x01(\v2\x19.overlord.v1.AdapterEventH\x00R\fadapterEvent\x12O\n" +
	"\x12overseer_heartbeat\x18\x12 \x01(\v2\x1e.overlord.v1.OverseerHeartbeatH\x00R\x11overseerHeartbeat\x12X\n" +
	"\x15overseer_disconnected\x18\x13 \x01(\v2!.overlord.v1.OverseerDisconnectedH\x00R\x14overseerDisconnected\x12:\n" +
	"\vwatch_ready\x18c \x01(\v2\x17.overlord.v1.WatchReadyH\x00R\n" +
	"watchReadyB\t\n" +
	"\apayload\"T\n" +
	"\n" +
	"RunStarted\x12#\n" +
	"\rworkflow_name\x18\x01 \x01(\tR\fworkflowName\x12!\n" +
	"\finitial_step\x18\x02 \x01(\tR\vinitialStep\"I\n" +
	"\fRunCompleted\x12\x1f\n" +
	"\vfinal_state\x18\x01 \x01(\tR\n" +
	"finalState\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"7\n" +
	"\tRunFailed\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\"U\n" +
	"\vStepEntered\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\"r\n" +
	"\vStepOutcome\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"U\n" +
	"\x0eStepTransition\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1f\n" +
	"\vvia_outcome\x18\x03 \x01(\tR\n" +
	"viaOutcome\"c\n" +
	"\aStepLog\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12.\n" +
	"\x06stream\x18\x02 \x01(\x0e2\x16.overlord.v1.LogStreamR\x06stream\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\tR\x05chunk\"}\n" +
	"\fAdapterEvent\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x18\n" +
	"\aadapter\x18\x02 \x01(\tR\aadapter\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\"4\n" +
	"\x11OverseerHeartbeat\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\"O\n" +
	"\x14OverseerDisconnected\x12\x1f\n" +
	"\voverseer_id\x18\x01 \x01(\tR\n" +
	"overseerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\f\n" +
	"\n" +
	"WatchReady*k\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x02\x12\x14\n" +
	"\x10LOG_STREAM_AGENT\x10\x03B\xac\x01\n" +
	"\x0fcom.overlord.v1B\vEventsProtoP\x01Z?github.com/brokenbots/overlord/shared/pb/overlord/v1;overlordv1\xa2\x02\x03OXX\xaa\x02\vOverlord.V1\xca\x02\vOverlord\\V1\xe2\x02\x17Overlord\\V1\\GPBMetadata\xea\x02\fOverlord::V1b\x06proto3"

var (
	file_overlord_v1_events_proto_rawDescOnce sync.Once
	file_overlord_v1_events_proto_rawDescData []byte
)

func file_overlord_v1_events_proto_rawDescGZIP() []byte {
	file_overlord_v1_events_proto_rawDescOnce.Do(func() {
		file_overlord_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_overlord_v1_events_proto_rawDesc), len(file_overlord_v1_events_proto_rawDesc)))
	})
	return file_overlord_v1_events_proto_rawDescData
}

var file_overlord_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_overlord_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_overlord_v1_events_proto_goTypes = []any{
	(LogStream)(0),                // 0: overlord.v1.LogStream
	(*Envelope)(nil),              // 1: overlord.v1.Envelope
	(*RunStarted)(nil),            // 2: overlord.v1.RunStarted
	(*RunCompleted)(nil),          // 3: overlord.v1.RunCompleted
	(*RunFailed)(nil),             // 4: overlord.v1.RunFailed
	(*StepEntered)(nil),           // 5: overlord.v1.StepEntered
	(*StepOutcome)(nil),           // 6: overlord.v1.StepOutcome
	(*StepTransition)(nil),        // 7: overlord.v1.StepTransition
	(*StepLog)(nil),               // 8: overlord.v1.StepLog
	(*AdapterEvent)(nil),          // 9: overlord.v1.AdapterEvent
	(*OverseerHeartbeat)(nil),     // 10: overlord.v1.OverseerHeartbeat
	(*OverseerDisconnected)(nil),  // 11: overlord.v1.OverseerDisconnected
	(*WatchReady)(nil),            // 12: overlord.v1.WatchReady
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 14: google.protobuf.Struct
}
var file_overlord_v1_events_proto_depIdxs = []int32{
	13, // 0: overlord.v1.Envelope.ts:type_name -> google.protobuf.Timestamp
	2,  // 1: overlord.v1.Envelope.run_started:type_name -> overlord.v1.RunStarted
	3,  // 2: overlord.v1.Envelope.run_completed:type_name -> overlord.v1.RunCompleted
	4,  // 3: overlord.v1.Envelope.run_failed:type_name -> overlord.v1.RunFailed
	5,  // 4: overlord.v1.Envelope.step_entered:type_name -> overlord.v1.StepEntered
	6,  // 5: overlord.v1.Envelope.step_outcome:type_name -> overlord.v1.StepOutcome
	7,  // 6: overlord.v1.Envelope.step_transition:type_name -> overlord.v1.StepTransition
	8,  // 7: overlord.v1.Envelope.step_log:type_name -> overlord.v1.StepLog
	9,  // 8: overlord.v1.Envelope.adapter_event:type_name -> overlord.v1.AdapterEvent
	10, // 9: overlord.v1.Envelope.overseer_heartbeat:type_name -> overlord.v1.OverseerHeartbeat
	11, // 10: overlord.v1.Envelope.overseer_disconnected:type_name -> overlord.v1.OverseerDisconnected
	12, // 11: overlord.v1.Envelope.watch_ready:type_name -> overlord.v1.WatchReady
	0,  // 12: overlord.v1.StepLog.stream:type_name -> overlord.v1.LogStream
	14, // 13: overlord.v1.AdapterEvent.data:type_name -> google.protobuf.Struct
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_overlord_v1_events_proto_init() }
func file_overlord_v1_events_proto_init() {
	if File_overlord_v1_events_proto != nil {
		return
	}
	file_overlord_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_RunStarted)(nil),
		(*Envelope_RunCompleted)(nil),
		(*Envelope_RunFailed)(nil),
		(*Envelope_StepEntered)(nil),
		(*Envelope_StepOutcome)(nil),
		(*Envelope_StepTransition)(nil),
		(*Envelope_StepLog)(nil),
		(*Envelope_AdapterEvent)(nil),
		(*Envelope_OverseerHeartbeat)(nil),
		(*Envelope_OverseerDisconnected)(nil),
		(*Envelope_WatchReady)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_overlord_v1_events_proto_rawDesc), len(file_overlord_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_overlord_v1_events_proto_goTypes,
		DependencyIndexes: file_overlord_v1_events_proto_depIdxs,
		EnumInfos:         file_overlord_v1_events_proto_enumTypes,
		MessageInfos:      file_overlord_v1_events_proto_msgTypes,
	}.Build()
	File_overlord_v1_events_proto = out.File
	file_overlord_v1_events_proto_goTypes = nil
	file_overlord_v1_events_proto_depIdxs = nil
}
